# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30002
  type: NodePort