apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas:  {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: {{ .Values.images.api }}
        ports:
        - containerPort: {{.Values.containerPort.api}}
