apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front
spec:
  replicas: {{ .Values.replicaCount.front }}
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
      - name: front-service
        image: {{.Values.images.front}}
       # ports:
       # - containerPort: {{.Values.containerPort.front}}

