apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
  labels:
    pv: pv-local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: {{ .Values.PersistentVolume.persistentVolumeReclaimPolicy }}
  hostPath:
    path: "/mnt/data"
  
