apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    service: front-service
spec:
  selector:
    app: front-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003
  type: NodePort
