apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    pv: pv-test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  # gcePersistentDisk:
  #   pdName: your-persistent-disk-name
  
