# create self-sign ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsign-clusterissuer
spec:
  selfSigned: {}
---
# create certidicates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scoresys-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: scoresys-selfsigned-ca
  secretName: scoresys-selfsigned-secret 
  duration: 360h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: selfsign-clusterissuer 
    kind: ClusterIssuer
    group: cert-manager.io
---
# ClusterIssuer，issuing CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-ca-issuer
spec:
  ca:
    secretName: scoresys-selfsigned-secret

