apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scoresys-com
spec:
  secretName: scoresys-tls
  duration: 10000h 
  renewBefore: 3600h 
  subject:
    organizations:
      - kay
  commonName: kay
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - scoresys.com
  ipAddresses:
    - 192.168.91.102
    - 192.168.91.103
    - 192.168.91.104
  issuerRef:
    name: my-ca-issuer 
    kind: ClusterIssuer
    group: cert-manager.io
