version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
    - 80:80
    volumes:
    - /root/nginx/html:/usr/share/nginx/html
    - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # authority


  mysql:
   # image: mysql:5.7.27
    build: ./mysql/
    restart: always
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
     # - MYSQL_DATABASE=sc_score_system
   # command: bash -c "mysql -u root -prootpassword sc_score_system < ./data.sql"

  scoresys:
    image: scoresys:latest
    restart: always
    build: ./backend
    ports:
    - 8081:8081
    depends_on:
      - mysql
