kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: secret-reader
rules:
  - apiGroups: [""] # the core API group
    resources: ["secret"]
    verbs: ["get", "watch", "list"]